// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAnchor: typeof import('@arco-design/web-vue')['Anchor']
    AAnchorLink: typeof import('@arco-design/web-vue')['AnchorLink']
    ABackTop: typeof import('@arco-design/web-vue')['BackTop']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
